version: 2.1
orbs:
  go: gotest/tools@0.0.9
executors:
  golang:
    docker:
      - image: cimg/go:1.18.8
    resource_class: medium
jobs:
  test:
    executor: golang
    steps:
      - checkout
      - run: go test -v -timeout 10m ./...
  mod-tidy-check:
    executor: golang
    steps:
      - checkout
      - go/mod-download
      - go/mod-tidy-check
  gofmt-check:
    executor: golang
    steps:
      - checkout
      - go/mod-download
      - run: "! go fmt ./... 2>&1 | read"
  lint-check:
    executor: golang
    steps:
      - checkout
      - go/mod-download
      - go/install-golangci-lint:
          gobin: $HOME/.local/bin
          version: 1.50.1
      - run:
          command: $HOME/.local/bin/golangci-lint run -v --concurrency 2
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - mod-tidy-check
      - lint-check
      - gofmt-check
      - test
